export const ARTICLES: string[] = [
  'caps lock',
  'caps lock alarm',
  'caps lock beep',
  'caps lock broken',
  'caps lock bulb',
  'caps lock by mouse',
  'caps lock diode',
  'caps lock disable',
  'caps lock fix',
  'caps lock free',
  'caps lock hardware',
  'caps lock indicator',
  'caps lock info',
  'caps lock led',
  'caps lock light',
  'caps lock lightbulb',
  'caps lock luminodiode',
  'caps lock no indicator',
  'caps lock no key',
  'caps lock notify',
  'caps lock off',
  'caps lock on',
  'caps lock on screen',
  'caps lock password',
  'caps lock software',
  'caps lock sound',
  'caps lock state',
  'caps lock status',
  'caps lock stuck',
  'caps lock switch',
  'caps lock tool',
  'caps lock turn off',
  'caps lock turn on',
  'caps lock utility',
  'caps lock windows',

  'num lock',
  'num lock alarm',
  'num lock beep',
  'num lock broken',
  'num lock bulb',
  'num lock by mouse',
  'num lock diode',
  'num lock disable',
  'num lock fix',
  'num lock free',
  'num lock hardware',
  'num lock indicator',
  'num lock info',
  'num lock led',
  'num lock light',
  'num lock lightbulb',
  'num lock luminodiode',
  'num lock no indicator',
  'num lock no key',
  'num lock notify',
  'num lock off',
  'num lock on',
  'num lock on screen',
  'num lock password',
  'num lock software',
  'num lock sound',
  'num lock state',
  'num lock status',
  'num lock stuck',
  'num lock switch',
  'num lock tool',
  'num lock turn off',
  'num lock turn on',
  'num lock utility',
  'num lock windows',

  'scroll lock',
  'scroll lock alarm',
  'scroll lock beep',
  'scroll lock broken',
  'scroll lock bulb',
  'scroll lock by mouse',
  'scroll lock diode',
  'scroll lock disable',
  'scroll lock fix',
  'scroll lock free',
  'scroll lock hardware',
  'scroll lock indicator',
  'scroll lock info',
  'scroll lock led',
  'scroll lock light',
  'scroll lock lightbulb',
  'scroll lock luminodiode',
  'scroll lock no indicator',
  'scroll lock no key',
  'scroll lock notify',
  'scroll lock off',
  'scroll lock on',
  'scroll lock on screen',
  'scroll lock password',
  'scroll lock software',
  'scroll lock sound',
  'scroll lock state',
  'scroll lock status',
  'scroll lock stuck',
  'scroll lock switch',
  'scroll lock tool',
  'scroll lock turn off',
  'scroll lock turn on',
  'scroll lock utility',
  'scroll lock windows',
];
