export const SOFTWARE: string[] = [
  'CaPNotifier',
  'Caps Lock Changer',
  'Caps Lock Indicator',
  'Caps Lock Status',
  'Caps Lock Viewer',
  'CapsLock',
  'CapsLock Indicator',
  'CapsLockDelay',
  'CapslockHater',
  'Clever Keyboard Indicator',
  'Cool Numpad',
  'Crazy Num Caps Scroll',
  'Disable Key',
  // 'DK%3AKeyboard-Status', // Must be "path friendly" name
  'DK Keyboard-Status',
  'DKOSD',
  'DKOSD - Caps-Lock Status',
  'Easy HR Caps Lock',
  'Extended Keys Manager',
  'FirstCap',
  'HddLed Indicator',
  'I Hate This Key',
  'KbdEdit',
  'Keyboard LEDs',
  'Keyndicate',
  'KeyPress Warning',
  'Keys',
  'Keyset',
  'KeyState',
  'Lower Case Switcher',
  'Microsoft IntelliType Pro',
  'NCSKeys',
  'Nodoka',
  'Num Lock Indicator',
  'NumCapsScroll Indicator',
  'ProKeyLock',
  'Recaps',
  'Scroll Lock Indicator',
  'ScrollLock',
  'Simply Alarming',
  'sMaRTcaPs',
  'Sysinternals Ctrl2cap',
  'Toggler',
  'TrayStatus',
  'Wireless Keyboard Indicator',
];
